manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nguyendown
      url-base: https://github.com/nguyendown
  projects:
    - name: zmk
      remote: nguyendown
      revision: zephyr-3.2+shield-cmake+charlieplex+sk-fixes+mouse+sensor-binding
      import: app/west.yml
  self:
    path: config
